language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - build-tools-19.1.0
     - platform-tools
     - tools
     
  licenses:
     - 'android-sdk-license-.+'
     
script: ./gradlew build connectedAndroidTest