# Test changes of this .travis.yml config before submitting them:
# http://lint.travis-ci.org/SecUpwN/Android-IMSI-Catcher-Detector

language: android

android:
  components:
# Uncomment the lines below if you want to
# use the latest revision of Android SDK Tools
     - build-tools-19.1.0
     - platform-tools
     - tools
     - extra
     
  licenses:
     - 'android-sdk-license-.+'
     
# Emulator Management: Create, Start and Wait
before_script:
     - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
     - emulator -avd test -no-skin -no-audio -no-window &
     - android-wait-for-emulator
     - adb shell input keyevent 82 &
     
script: ./gradlew build connectedAndroidTest

env:
  global:
# The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
# via the "travis encrypt" command using the project repo's public key
   - secure: "jRKgZfeAxDhqDIrySBESiij3Ot9cmVQ4CMB+IVpmf7Xjfek6By1ba7Y1lgMdLRPgvLkj3k5mMx1BMx2yeSCBp/+TZJ6Ezj3EVJ6HS2ctkAH4KzsiqlSCKiRgfOqKgzfnftCkNzXCEE3XLVLcv4iT5Ru/EBG85kEDViGrDBP+PxA="

addons:
  coverity_scan:
    project:
      name: "SecUpwN/Android-IMSI-Catcher-Detector"
    notification_email: perfect-privacy@secure-mail.biz; xdae3v3a@gmail.com; toby@tobykurien.com
    build_command_prepend: "echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a"
    build_command:   "./gradlew build connectedAndroidTest"
    branch_pattern: master
